apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: myapp
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  
  type: NodePort
