apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: mohamedashraf14/backend:latest
        ports:
        - containerPort: 3000