apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: myapp
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
